import assert from "node:assert/strict";
import test from "node:test";
import { appendFileSync, mkdtempSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const root = mkdtempSync(join(tmpdir(), "index-updates-"));
process.env.PI_THREAD_PHASE_STORE_DIR = root;
test.after(() => rmSync(root, { recursive: true, force: true }));
const { INDEX_FILE, ensureStore, readIndexUpdates } = await import("../lib/store.mjs");

test("incremental index discovery bounds bursts, retains partial records, and resets on replacement/truncation", () => {
  ensureStore();
  const line = id => JSON.stringify({ eventId: id, type: "workflow_end", runId: "run", timestamp: new Date().toISOString() }) + "\n";
  writeFileSync(INDEX_FILE, line("history"));
  let { cursor } = readIndexUpdates();
  assert.equal(cursor.offset, Buffer.byteLength(line("history")));
  const partial = line("partial-π");
  const split = Buffer.from(partial).indexOf(Buffer.from("π")) + 1;
  appendFileSync(INDEX_FILE, Buffer.from(partial).subarray(0, split));
  let next = readIndexUpdates(cursor);
  assert.deepEqual(next.events, []);
  assert.deepEqual(next.cursor, cursor, "incomplete UTF-8 record is retried, not consumed");
  assert.deepEqual(readIndexUpdates().cursor, cursor, "startup also retains the partial record");
  appendFileSync(INDEX_FILE, Buffer.from(partial).subarray(split));
  appendFileSync(INDEX_FILE, Array.from({ length: 6000 }, (_, i) => line(`burst-${i}`)).join(""));
  next = readIndexUpdates(cursor);
  assert.equal(next.events.length, 5000);
  assert.equal(next.events[0].eventId, "partial-π");
  cursor = next.cursor;
  next = readIndexUpdates(cursor);
  assert.equal(next.events.length, 1001);
  assert.equal(next.events.at(-1).eventId, "burst-5999");
  cursor = next.cursor;
  assert.deepEqual(readIndexUpdates(cursor).events, []);
  renameSync(INDEX_FILE, `${INDEX_FILE}.old`);
  writeFileSync(INDEX_FILE, line("replacement"));
  next = readIndexUpdates(cursor);
  assert.equal(next.events[0].eventId, "replacement");
  writeFileSync(INDEX_FILE, line("short"));
  next = readIndexUpdates(next.cursor);
  assert.equal(next.events[0].eventId, "short");
  cursor = next.cursor;
  appendFileSync(INDEX_FILE, "bad-json\n" + line("after-corrupt"));
  next = readIndexUpdates(cursor);
  assert.equal(next.events[0].eventId, "after-corrupt");
  assert.equal(next.events.parseErrors.length, 1, "same tolerant diagnostics as general readIndex");
  cursor = next.cursor;
  appendFileSync(INDEX_FILE, "x".repeat(512 * 1024));
  assert.throws(() => readIndexUpdates(cursor), /Oversized partial/);
  assert.throws(() => readIndexUpdates(), /Oversized partial/);
});
